/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.menus;

import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.red;
import java.awt.Font;
import javax.swing.ButtonGroup;

/**
 *
 * @author 2dam
 */
public class menus extends javax.swing.JFrame {

    /**
     * Creates new form menus
     */
    public menus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Cambio = new javax.swing.JLabel();
        BarraSelectora = new javax.swing.JMenuBar();
        Fondo = new javax.swing.JMenu();
        FondoColorRojo = new javax.swing.JMenuItem();
        FondoColorVerde = new javax.swing.JMenuItem();
        FondoColorAmarillo = new javax.swing.JMenuItem();
        ColorTexto = new javax.swing.JMenu();
        TextoColorRojo = new javax.swing.JMenuItem();
        TextoColorVerde = new javax.swing.JMenuItem();
        TextoColorAmarillo = new javax.swing.JMenuItem();
        Temas = new javax.swing.JMenu();
        Tema1 = new javax.swing.JMenuItem();
        Tema2 = new javax.swing.JMenuItem();
        TamañoLetra = new javax.swing.JMenu();
        Tamano5 = new javax.swing.JMenuItem();
        Tamano10 = new javax.swing.JMenuItem();
        Tamano15 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cambio.setText("Hola");
        Cambio.setOpaque(true);

        Fondo.setText("Fondo");
        Fondo.setBorderPainted(false);
        Fondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoActionPerformed(evt);
            }
        });

        FondoColorRojo.setText("FondoColorRojo");
        FondoColorRojo.setOpaque(true);
        FondoColorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoColorRojoActionPerformed(evt);
            }
        });
        Fondo.add(FondoColorRojo);

        FondoColorVerde.setText("FondoColorVerde");
        FondoColorVerde.setOpaque(true);
        FondoColorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoColorVerdeActionPerformed(evt);
            }
        });
        Fondo.add(FondoColorVerde);

        FondoColorAmarillo.setText("FondoColorAmarillo");
        FondoColorAmarillo.setOpaque(true);
        FondoColorAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoColorAmarilloActionPerformed(evt);
            }
        });
        Fondo.add(FondoColorAmarillo);

        BarraSelectora.add(Fondo);

        ColorTexto.setText("Color texto");

        TextoColorRojo.setText("ColorRojo");
        TextoColorRojo.setActionCommand("ColorRojo");
        TextoColorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoColorRojoActionPerformed(evt);
            }
        });
        ColorTexto.add(TextoColorRojo);

        TextoColorVerde.setText("ColorVerde");
        TextoColorVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoColorVerdeActionPerformed(evt);
            }
        });
        ColorTexto.add(TextoColorVerde);

        TextoColorAmarillo.setText("ColorAmarillo");
        TextoColorAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoColorAmarilloActionPerformed(evt);
            }
        });
        ColorTexto.add(TextoColorAmarillo);

        BarraSelectora.add(ColorTexto);

        Temas.setText("Temas");

        Tema1.setText("Tema1");
        Tema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tema1ActionPerformed(evt);
            }
        });
        Temas.add(Tema1);

        Tema2.setText("Tema2");
        Tema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tema2ActionPerformed(evt);
            }
        });
        Temas.add(Tema2);

        BarraSelectora.add(Temas);

        TamañoLetra.setText("Tamaño de letra");

        Tamano5.setText("5");
        Tamano5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tamano5ActionPerformed(evt);
            }
        });
        TamañoLetra.add(Tamano5);

        Tamano10.setText("10");
        Tamano10.setToolTipText("");
        Tamano10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tamano10ActionPerformed(evt);
            }
        });
        TamañoLetra.add(Tamano10);

        Tamano15.setText("15");
        Tamano15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tamano15ActionPerformed(evt);
            }
        });
        TamañoLetra.add(Tamano15);

        BarraSelectora.add(TamañoLetra);

        setJMenuBar(BarraSelectora);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cambio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoActionPerformed
             
       
    }//GEN-LAST:event_FondoActionPerformed

    private void FondoColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoColorRojoActionPerformed

        Cambio.setBackground(Color.red);
        
    }//GEN-LAST:event_FondoColorRojoActionPerformed

    private void FondoColorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoColorVerdeActionPerformed
         Cambio.setBackground(Color.green);
    }//GEN-LAST:event_FondoColorVerdeActionPerformed

    private void FondoColorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoColorAmarilloActionPerformed
         Cambio.setBackground(Color.yellow);      
    }//GEN-LAST:event_FondoColorAmarilloActionPerformed

    private void TextoColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoColorRojoActionPerformed
         Cambio.setForeground(Color.red);    
    }//GEN-LAST:event_TextoColorRojoActionPerformed

    private void TextoColorVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoColorVerdeActionPerformed
        Cambio.setForeground(Color.green); 
    }//GEN-LAST:event_TextoColorVerdeActionPerformed

    private void TextoColorAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoColorAmarilloActionPerformed
        Cambio.setForeground(Color.yellow); 
    }//GEN-LAST:event_TextoColorAmarilloActionPerformed

    private void Tema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tema1ActionPerformed
        Cambio.setForeground(Color.blue); 
        Cambio.setBackground(Color.pink);
    }//GEN-LAST:event_Tema1ActionPerformed

    private void Tema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tema2ActionPerformed
         Cambio.setForeground(Color.pink); 
        Cambio.setBackground(Color.blue);
    }//GEN-LAST:event_Tema2ActionPerformed

    private void Tamano5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tamano5ActionPerformed
       Cambio.setFont(new Font("Segoe", Font. BOLD, 5));
    }//GEN-LAST:event_Tamano5ActionPerformed

    private void Tamano10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tamano10ActionPerformed
         Cambio.setFont(new Font("Segoe", Font. BOLD, 10));
    }//GEN-LAST:event_Tamano10ActionPerformed

    private void Tamano15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tamano15ActionPerformed
        Cambio.setFont(new Font("Segoe", Font. BOLD, 15));
    }//GEN-LAST:event_Tamano15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraSelectora;
    private javax.swing.JLabel Cambio;
    private javax.swing.JMenu ColorTexto;
    private javax.swing.JMenu Fondo;
    private javax.swing.JMenuItem FondoColorAmarillo;
    private javax.swing.JMenuItem FondoColorRojo;
    private javax.swing.JMenuItem FondoColorVerde;
    private javax.swing.JMenuItem Tamano10;
    private javax.swing.JMenuItem Tamano15;
    private javax.swing.JMenuItem Tamano5;
    private javax.swing.JMenu TamañoLetra;
    private javax.swing.JMenuItem Tema1;
    private javax.swing.JMenuItem Tema2;
    private javax.swing.JMenu Temas;
    private javax.swing.JMenuItem TextoColorAmarillo;
    private javax.swing.JMenuItem TextoColorRojo;
    private javax.swing.JMenuItem TextoColorVerde;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
